In [1]:
import pandas as pd
import folium
from IPython.display import IFrame
from folium import plugins
from folium.plugins import MarkerCluster

In [2]:

file_path = '../resources/crypto_final.csv'
crypto_data_df = pd.read_csv(file_path)
crypto_data_df.head()

,countries,Latitude,Longitude,pop2023,Number_of_Crypto_Ownership,gdpPerCapita
0,India,20.593684,78.962880,1428627663,103317638,2588.727619
1,China,35.861660,104.195397,1425671352,58187265,12420.125970
2,United States,37.090240,-95.712891,339996563,44959854,78842.899610
3,Vietnam,14.058324,108.277199,98858950,20301468,4355.438237
4,Pakistan,30.375321,69.345116,240485658,15400547,1389.161360

In [3]:
bins = [0, 500000, 2000000, 8000000, 1000000000]


crypto_data_df['Crypto_Ownership_Category'] = pd.cut(crypto_data_df['Number_of_Crypto_Ownership'], bins=bins, labels=['<500k', '500k-2M', '2M-8M', '8M-100M'])

crypto_data_df.tail()

,countries,Latitude,Longitude,pop2023,Number_of_Crypto_Ownership,gdpPerCapita,Crypto_Ownership_Category
40,Iraq,33.223191,43.679291,45504560,822055,5480.931991,500k-2M
41,Ghana,7.946527,-1.023194,34121985,738074,2203.377227,500k-2M
42,Australia,-25.274398,133.775136,26439111,705743,63211.338710,500k-2M
43,Ecuador,-1.831239,-78.183406,18190484,675156,6458.270110,500k-2M
44,Cambodia,12.565679,104.990963,16944826,565577,1807.223251,500k-2M

In [4]:
mymap = folium.Map(location=[crypto_data_df['Latitude'].iloc[0], crypto_data_df['Longitude'].iloc[0]], zoom_start=4)


bins = [0, 2000000, 5000000, 8000000, 1000000000]


crypto_data_df['Crypto_Ownership_Category'] = pd.cut(crypto_data_df['Number_of_Crypto_Ownership'], bins=bins, labels=['< 2,000,000', '2,000,000 - 5,000,000', '5,000,000 - 8,000,000', '> 8,000,000'])


categories = ['< 2,000,000', '2,000,000 - 5,000,000', '5,000,000 - 8,000,000', '> 8,000,000']
crypto_data_df['Crypto_Ownership_Category'] = pd.Categorical(crypto_data_df['Crypto_Ownership_Category'], categories=categories, ordered=True)




marker_cluster = MarkerCluster().add_to(mymap)

colors = {
    '< 2,000,000': 'green',
    '2,000,000 - 5,000,000': 'yellow',
    '5,000,000 - 8,000,000': 'orange',
    '> 8,000,000': 'red',
    '>100000000 ': 'gray'
}
#df['Crypto_Ownership_Category'].fillna('Unknown', inplace=True)


for index, row in crypto_data_df.iterrows():
    color = colors[row['Crypto_Ownership_Category']]
 
    popup_text = f"<b>Country:</b> {row['countries']}<br>" \
                 f"<b>Population 2023:</b> {row['pop2023']}<br>" \
                 f"<b>GDP per Capita:</b> {row['gdpPerCapita']}<br>" \
                 f"<b>Crypto Ownership:</b> {row['Number_of_Crypto_Ownership']}"

    folium.Marker(
        [row['Latitude'], row['Longitude']],
        popup=folium.Popup(popup_text, max_width=300),
        icon=folium.Icon(color=color)
    ).add_to(marker_cluster)


legend_html = '''
     <div style="position: fixed; 
     bottom: 100px; left: 100px; width: 200px; height: 200px; 
     border:5px solid grey; z-index:9999; font-size:15px;
     background-color:white; opacity: 1;
     ">
     &nbsp; Crypto Ownership <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:green"></i>&nbsp; < 2,000,000 <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:yellow"></i>&nbsp; 2,000,000 - 5,000,000 <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:orange"></i>&nbsp; 5,000,000 - 8,000,000 <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:red"></i>&nbsp; > 8,000,000 <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:gray"></i>&nbsp; Unknown <br>
      </div>
     '''
mymap.get_root().html.add_child(folium.Element(legend_html))


mymap.save('my_map_with_legend.html')

IFrame(src='my_map_with_legend.html', width='100%', height='750px')

C:\Users\User\AppData\Local\Temp\ipykernel_17480\3446080822.py:39: UserWarning: color argument of Icon should be one of: {'pink', 'orange', 'green', 'darkgreen', 'cadetblue', 'black', 'lightred', 'lightgray', 'blue', 'white', 'darkpurple', 'darkred', 'purple', 'lightgreen', 'red', 'beige', 'lightblue', 'gray', 'darkblue'}.
  icon=folium.Icon(color=color)

# Stock Market Map

In [5]:

file_path = '../resources/Stock_final.csv'
Stock_data_df = pd.read_csv(file_path)
Stock_data_df.head(10)

,Countries,Latitude,Longitude,imfGDP,gdpPerCapita,Total_market_cap_of_GDP,Number_of_domestic_companies_listed
0,United States,37.090240,-95.712891,2.690000e+13,78842.899610,194.5,"4,266"
1,China,35.861660,104.195397,1.770000e+13,12420.125970,126.7,"3,754"
2,Germany,51.165691,10.451526,4.430000e+12,53209.710020,60.0,438
3,Japan,36.204824,138.252924,4.230000e+12,34500.616450,65.1,"4,154"
4,India,20.593684,78.962880,3.730000e+12,2588.727619,120.0,"5,270"
5,United Kingdom,55.378051,-3.435973,3.330000e+12,49028.685220,100.0,"1,858"
6,France,46.227638,2.213749,3.050000e+12,46993.434060,84.9,457
7,Italy,41.871940,12.567380,2.190000e+12,37242.998640,36.5,290
8,Brazil,-14.235004,-51.925280,2.130000e+12,9772.268032,68.4,345
9,Canada,56.130366,-106.346771,2.120000e+12,54154.179790,160.7,"3,922"

In [6]:
import pandas as pd

bins = [0, 5000, 10000, 20000, 50000, 100000, 1000000]
labels = ['<5k', '5k-10k', '10k-20k', '20k-50k', '50k-100k', '<1M']


Stock_data_df['gdpPerCapita'] = pd.to_numeric(Stock_data_df['gdpPerCapita'], errors='coerce')


Stock_data_df['Range_gdpPerCapita'] = pd.cut(Stock_data_df['gdpPerCapita'], bins=bins, labels=labels)


Stock_data_df.head(100)

,Countries,Latitude,Longitude,imfGDP,gdpPerCapita,Total_market_cap_of_GDP,Number_of_domestic_companies_listed,Range_gdpPerCapita
0,United States,37.090240,-95.712891,2.690000e+13,78842.899610,194.5,"4,266",50k-100k
1,China,35.861660,104.195397,1.770000e+13,12420.125970,126.7,"3,754",10k-20k
2,Germany,51.165691,10.451526,4.430000e+12,53209.710020,60.0,438,50k-100k
3,Japan,36.204824,138.252924,4.230000e+12,34500.616450,65.1,"4,154",20k-50k
4,India,20.593684,78.962880,3.730000e+12,2588.727619,120.0,"5,270",<5k
...,...,...,...,...,...,...,...,...
95,Seychelles,-4.679574,55.491977,2.085000e+09,19258.657160,71.9,40,10k-20k
96,Bermuda,32.321384,-64.757370,0.000000e+00,113093.143100,39.6,13,<1M
97,Cayman Islands,19.513469,-80.566956,0.000000e+00,83116.721370,6.4,4,50k-100k
98,Sri Lanka,7.873054,80.771797,0.000000e+00,3886.633449,19.8,283,<5k
99,Palestine,31.947400,35.227200,0.000000e+00,3282.424286,22.2,46,<5k

In [7]:

mymap = folium.Map(location=[Stock_data_df['Latitude'].mean(),Stock_data_df['Longitude'].mean()], zoom_start=4)


marker_cluster = MarkerCluster().add_to(mymap)


colors = {
    '<5k': 'green',
    '5k-10k': 'yellow',
    '10k-20k': 'orange',
    '20k-50k': 'red',
    '50k-100k': 'blue',
    '1M': 'purple'  
}


for index, row in Stock_data_df.iterrows():

    color = colors.get(row['Range_gdpPerCapita'], 'gray')  # Default color for unknown values

    popup_text = f"<b>Country:</b> {row['Countries']}<br>" \
                 f"<b>gdpPerCapita:</b> {row['gdpPerCapita']}<br>" \
                 f"<b>Number_of_domestic_companies_listed:</b> {row['Number_of_domestic_companies_listed']}"

    folium.Marker(
        [row['Latitude'], row['Longitude']],
        popup=folium.Popup(popup_text, max_width=300),
        icon=folium.Icon(color=color)
    ).add_to(marker_cluster)

legend_html = '''
     <div style="position: fixed; 
     bottom: 80px; left: 80px; width: 170px; height: 170px; 
     border:4px solid grey; z-index:9999; font-size:14px;
     background-color:white; opacity: 1;
     ">
     &nbsp; GDP per Capita <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:green"></i>&nbsp; < 5,000 <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:yellow"></i>&nbsp; 5,000 - 10,000 <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:orange"></i>&nbsp; 10,000 - 20,000 <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:red"></i>&nbsp; 20,000 - 50,000 <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:blue"></i>&nbsp; 50,000 - 100,000 <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:purple"></i>&nbsp; 1M <br>
     &nbsp; <i class="fa fa-circle fa-1x" style="color:gray"></i>&nbsp; Unknown <br>
     </div>
'''

mymap.get_root().html.add_child(folium.Element(legend_html))


mymap.save('my_map_with_legend.html')


IFrame(src='my_map_with_legend.html', width='100%', height=750)

C:\Users\User\AppData\Local\Temp\ipykernel_17480\1312001605.py:28: UserWarning: color argument of Icon should be one of: {'pink', 'orange', 'green', 'darkgreen', 'cadetblue', 'black', 'lightred', 'lightgray', 'blue', 'white', 'darkpurple', 'darkred', 'purple', 'lightgreen', 'red', 'beige', 'lightblue', 'gray', 'darkblue'}.
  icon=folium.Icon(color=color)